spring:
  application:
    name: zipkin-client-hello
  # 配置分布式追踪系统的服务端
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9412

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

