spring:
  application:
    name: service-ribbon

server:
  port: 8764

eureka:
  client:
    # 指定服务注册中心的位置
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}