server:
  port: 8881

spring:
  application:
    name: config-client
eureka:
  instance:
    # 以 IP:port 注册本服务
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/