server:
  port: 8881

spring:
  application:
    # spring-cloud-config配置中心，要有以该name命名的properties或yml文件；如config-client-pro.properties，config-client-dev.yml
    name: config-client
eureka:
  instance:
    # 以 IP:port 注册本服务
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/